// User reducer types
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED'
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED'
export const SET_USER = 'SET_USER'
export const LOADING_USER = 'LOADING_USER'
export const NO_ONLINE_USERS = 'NO_ONLINE_USERS '
export const SET_ONLINE_USERS = 'SET_ONLINE_USERS'

// UI reducer types
export const SET_ERRORS = 'SET_ERRORS'
export const LOADING_UI = 'LOADING_UI'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'
export const LOADING_DATA = 'LOADING_DATA'
export const STOP_LOADING_UI = 'STOP_LOADING_UI'
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD'
export const LOGOUT_USER = 'LOGOUT_USER'
export const SUGGEST_USERS = 'SUGGEST_USERS'
// Data reducer types

export const SET_POST = 'SET_POST'
export const CLEAN_POSTS = 'CLEAN_POSTS'
export const LIKE_POST = 'LIKE_POST'
export const UNLIKE_POST = 'UNLIKE_POST'
export const DELETE_POST = 'DELETE_POST'
export const COMMENT_POST = 'COMMENT_POST'
export const SUBMIT_POST = 'SUBMIT_POST'
export const SUBMIT_COMMENT = 'SUBMIT_COMMENT'
export const GET_POST = 'GET_POST'

export const SET_SELECTED_USER = 'SET_SELECTED_USER'
export const SET_FOLLOWERS = 'SET_FOLLOWERS'

export const UPLOADING_IMAGE = 'UPLOADING_IMAGE'
export const UPLOADING_IMAGE_SUCESS = 'UPLOADING_IMAGE_SUCESS'
export const DELETE_IMAGE = 'DELETE_IMAGE'

export const SEND_FOLLOW_REQUEST = 'SEND_FOLLOW_REQUEST'
export const ACCEPT_FOLLOW_REQUEST = 'ACCEPT_FOLLOW_REQUEST'
export const SET_FOLLOW_REQUESTS = 'SET_FOLLOW_REQUESTS'
export const DECLINE_REQUEST = 'DELETE_IMAGE'

export const SET_FOLLOWER = 'SET_FOLLOWER'
export const UNFOLLOW_USER = 'UNFOLLOW_USER'

//Messages reducer types

export const SET_MESSAGE = "SET_MESSAGE";
export const LOAD_MESSAGES = "LOAD_MESSAGES";
export const LOAD_CONVERSATIONS = "LOAD_CONVERSATIONS";
export const LOAD_CONVERSATIONS_SUCESS = "LOAD_CONVERSATIONS_SUCESS";
export const LOAD_SUCESS_MESSAGE = "LOAD_SUCESS";
export const SET_SUCESS_MESSAGE = "SET_SUCESS";
export const LOAD_FAILURE_MESSAGES = "LOAD_FAILURE";
export const SET_FAILURE_MESSAGES = "SET_FAILURE";

//MESSAGES TYPES
export const MESSAGE_UPDATE = "MESSAGE_UPDATE";